apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-deployment-demo
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/M-krithika/argocd/argocd-demo-app.yaml.git
    targetRevision: HEAD
    path: .

  destination: 
    server: https://kubernetes.default.svc
    namespace: argocd-demo

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
